### ISSUE TITLE
Specification of propensity functions?

### ISSUE THREAD

**Issue by slwu89** [mehalter/Petri.jl#34]
Hi,

I had a question on what are the allowable elements of the LVector object that holds the rate/propensity functions. For example in this line: https://github.com/mehalter/Petri.jl/blob/master/examples/epidemiology.jl#L35 infection occurs with propensity `0.5/sum(u0)` but is there a way to allow the propensity to be an arbitrary function of current state? For example if the state vector is `u` we might want to use `0.5 / sum(u)` if births and deaths are allowed. More generally how can one use rate/propensity functions that vary with time (inhomogeneous)?

Apologies if this is already documented somewhere but I did not find it easily. Also with some help, I would be very happy to write examples for other users!

**Comment by mehalter** [comment]
This is a good question and should be documented more. Currently there is support for the rates to be a function that varies with time. The current implementation doesn't support rates being based on the current state of the system as of now, this should be fixed. For an example of changing rates over time, here is an example for a simple SIR epidemiology model where the rate of infection decreases overtime (notice the rate of infection for the variable β):

```julia
using Petri
using LabelledArrays
using Plots
using DiffEqJump

S  = [:S,:I,:R]
Δ  = LVector(
       inf=(LVector(S=1, I=1), LVector(I=2)),
       rec=(LVector(I=1),      LVector(R=1)),
     )
sir = Petri.Model(S, Δ)

u0 = LVector(S=990.0, I=10.0, R=0.0)
tspan = (0.0,40.0)
β = LVector(inf=(t->((3/sum(u0))/(t+1))), rec=0.25);

prob = JumpProblem(sir, u0, tspan, β)
sol = DiffEqJump.solve(prob,SSAStepper())

plot(sol)
```

**Comment by slwu89** [comment]
Thank you for the quick answer @mehalter! So the elements of β are allowed to be constants, or functions of time at present. I'll be excited to see the state dependent rate update.

**Comment by mehalter** [comment]
Yeah, I just made a simple change that will add state dependent rates. Instead of being either constants or functions of time, it will now be constants, function of time, or functions of state and time, so this code would become

```julia
using Petri
using LabelledArrays
using Plots
using DiffEqJump

S  = [:S,:I,:R]
Δ  = LVector(
       inf=(LVector(S=1, I=1), LVector(I=2)),
       rec=(LVector(I=1),      LVector(R=1)),
     )
sir = Petri.Model(S, Δ)

u0 = LVector(S=990.0, I=10.0, R=0.0)
tspan = (0.0,40.0)
β = LVector(inf=((u,t)->((3/sum(u))/(t+1))), rec=0.25);

# the following syntax is still valid
# it assumes if there is a single parameter it is a function of just time
# β = LVector(inf=(t->((3/sum(u0))/(t+1))), rec=0.25);

prob = JumpProblem(sir, u0, tspan, β)
sol = DiffEqJump.solve(prob,SSAStepper())

plot(sol)
```

**Comment by mehalter** [comment]
This has been added with release v1.2 (#35)
